AWSTemplateFormatVersion: '2010-09-09'
Description: 'Static website hosting on S3'
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'cloudpipe-website-kk'
      WebsiteConfiguration:
        IndexDocument: 'index.html'

      PublicAccessBlockConfiguration:
        RestrictPublicBuckets: false

  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
         - Effect: Allow
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${S3Bucket}/*'